title: Devin Bernosky
description: "Move fast and break things. As declaratively and atomically as possible."
author: Devin
timezone: America/Los_Angeles
twitter:
  username: devindudeman
  card: summary_large_image
url: "https://devin.fitzsky.com"
baseurl: ""
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Devin
      image: /assets/images/og-default.png
  - scope:
      path: ""
    values:
      layout: page
      image: /assets/images/og-default.png
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
